apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rhdhpai-581-sep09-3
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-lyoon/rhdhpai-581-sep09-3:faa775c5158de806aa102ee12064a026f27290de@sha256:8fb1f879ece7256f31ff3d0bf7519a87548e9de31e9e0b1707c51892d01050d2 # use pre-built to bootstrap
          name: app-inference
